name: Conventional Commits Workflow

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commits
        shell: bash
        run: |
          git fetch --depth=0 --tags || true
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx -y @commitlint/cli@latest \
              -x @commitlint/config-conventional \
              --from="${{ github.event.pull_request.base.sha }}" \
              --to="${{ github.sha }}" \
              --verbose
          else
            npx -y @commitlint/cli@latest \
              -x @commitlint/config-conventional \
              --from="$(git rev-list --max-parents=0 HEAD)" \
              --to=HEAD \
              --verbose
          fi
