name: format
on:
  push: { branches: [ main, development ] }
  pull_request: { branches: [ main, development ] }
jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
          run_install: true
      - run: pnpm format
